apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prom
spec:
  ports:
    - port: 9090
  selector:
    app: prom
  type: NodePort
---


apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config
  labels: 
    app: prom
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    scrape_configs:
     - job_name: 'prometheus'
       static_configs:
       - targets: ['localhost:9090']
     - job_name: 'node'
       static_configs:
       - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pv-claim
  labels:
    app: prom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prom
spec:
  selector:
    matchLabels:
      app: prom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
      - image: prom/prometheus
        name: prompod
        ports:
        - containerPort: 9090
          name: prompod
        volumeMounts:
        - name: promlogs
          mountPath: /prometheus/data
        volumeMounts:
        - name: promconfig
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: promlogs
        persistentVolumeClaim:
          claimName: prom-pv-claim
      - name: promconfig
        configMap:
          name: prom-config
